#!/bin/sh

COMMIT_MESSAGE=$(cat "$1")

export COMMIT_MESSAGE
python3 .git/script/gitscript.py

# commit folyamatot 0 folytatjuk 1 megállítjuk
RETURN_VALUE=$?
#echo "A Python kód visszatérési értéke: $RETURN_VALUE"
exit $RETURN_VALUE
